# Import

In [1]:
import sys
sys.path.append("..")
from hbsir import data_engine

# Loading data

## Load Standard Data

In [2]:
data_engine.load_table('food', 1400)

,ID,Code,Provision_Method,Amount,Price,Expenditure
0,10004004227,11112,Purchase,10.00,250000.0,2500000.0
1,10004004227,11142,Purchase,10.00,30000.0,300000.0
2,10004004227,11143,Purchase,10.00,30000.0,300000.0
3,10004004227,11174,Purchase,2.00,350000.0,700000.0
4,10004004227,11211,Purchase,2.00,1300000.0,2600000.0
...,...,...,...,...,...,...
1127128,23003707026,11924,Non_Agricultural_Work,0.63,452380.0,285000.0
1127129,23003707026,12112,Non_Agricultural_Work,0.50,2500000.0,1250000.0
1127130,23003707026,12212,Non_Agricultural_Work,0.00,NaN,200000.0
1127131,23003707035,12211,Purchase,0.00,NaN,150000.0
1127132,23003707035,12213,Purchase,0.00,NaN,150000.0

## Load Original Data

In [3]:
data_engine.load_table('food', 1400, standard=False)

,ID,Code,Provision_Method,Grams,Kilos,Price,Expenditure
0,10004004227,11112,Purchase,NaN,10.0,250000.0,2500000.0
1,10004004227,11142,Purchase,NaN,10.0,30000.0,300000.0
2,10004004227,11143,Purchase,NaN,10.0,30000.0,300000.0
3,10004004227,11174,Purchase,NaN,2.0,350000.0,700000.0
4,10004004227,11211,Purchase,NaN,2.0,1300000.0,2600000.0
...,...,...,...,...,...,...,...
1127128,23003707026,11924,Non_Agricultural_Work,630.0,NaN,452380.0,285000.0
1127129,23003707026,12112,Non_Agricultural_Work,500.0,NaN,2500000.0,1250000.0
1127130,23003707026,12212,Non_Agricultural_Work,NaN,NaN,NaN,200000.0
1127131,23003707035,12211,Purchase,NaN,NaN,NaN,150000.0
1127132,23003707035,12213,Purchase,NaN,NaN,NaN,150000.0

## Add Year to Data

In [4]:
data_engine.load_table('food', 1400, add_year=True)

,Year,ID,Code,Provision_Method,Amount,Price,Expenditure
0,1400,10004004227,11112,Purchase,10.00,250000.0,2500000.0
1,1400,10004004227,11142,Purchase,10.00,30000.0,300000.0
2,1400,10004004227,11143,Purchase,10.00,30000.0,300000.0
3,1400,10004004227,11174,Purchase,2.00,350000.0,700000.0
4,1400,10004004227,11211,Purchase,2.00,1300000.0,2600000.0
...,...,...,...,...,...,...,...
1127128,1400,23003707026,11924,Non_Agricultural_Work,0.63,452380.0,285000.0
1127129,1400,23003707026,12112,Non_Agricultural_Work,0.50,2500000.0,1250000.0
1127130,1400,23003707026,12212,Non_Agricultural_Work,0.00,NaN,200000.0
1127131,1400,23003707035,12211,Purchase,0.00,NaN,150000.0
1127132,1400,23003707035,12213,Purchase,0.00,NaN,150000.0

**Note**

- If only one year loaded, the default value of add_year is false, otherwise it's true.

## Load Data for Range of Years

In [5]:
data_engine.load_table('food', 1396, 1400)

,Year,ID,Code,Provision_Method,Amount,Price,Expenditure
0,1396,10007007329,11142,Purchase,6.00,16000.0,96000.0
1,1396,10007007329,11143,Purchase,6.00,16000.0,96000.0
2,1396,10007007329,11144,Purchase,4.00,16000.0,64000.0
3,1396,10007007329,11152,Purchase,2.00,48000.0,96000.0
4,1396,10007007329,11164,Purchase,3.00,39000.0,117000.0
...,...,...,...,...,...,...,...
1127128,1400,23003707026,11924,Non_Agricultural_Work,0.63,452380.0,285000.0
1127129,1400,23003707026,12112,Non_Agricultural_Work,0.50,2500000.0,1250000.0
1127130,1400,23003707026,12212,Non_Agricultural_Work,0.00,NaN,200000.0
1127131,1400,23003707035,12211,Purchase,0.00,NaN,150000.0
1127132,1400,23003707035,12213,Purchase,0.00,NaN,150000.0

# Adding Attributes and Translations

## Check Available Attributes

In [6]:
data_engine._Attributes

typing.Literal['Urban-Rural', 'Province', 'Region']

## Add Household Attributes to Table

In [7]:
year = 1400

df = data_engine.load_table('food', year)

data_engine.add_attribute(df, year, ["Urban-Rural", "Province"])

,ID,Code,Provision_Method,Amount,Price,Expenditure,Urban-Rural,Province
0,10004004227,11112,Purchase,10.00,250000.0,2500000.0,Urban,Markazi
1,10004004227,11142,Purchase,10.00,30000.0,300000.0,Urban,Markazi
2,10004004227,11143,Purchase,10.00,30000.0,300000.0,Urban,Markazi
3,10004004227,11174,Purchase,2.00,350000.0,700000.0,Urban,Markazi
4,10004004227,11211,Purchase,2.00,1300000.0,2600000.0,Urban,Markazi
...,...,...,...,...,...,...,...,...
1127128,23003707026,11924,Non_Agricultural_Work,0.63,452380.0,285000.0,Rural,Alborz
1127129,23003707026,12112,Non_Agricultural_Work,0.50,2500000.0,1250000.0,Rural,Alborz
1127130,23003707026,12212,Non_Agricultural_Work,0.00,NaN,200000.0,Rural,Alborz
1127131,23003707035,12211,Purchase,0.00,NaN,150000.0,Rural,Alborz
1127132,23003707035,12213,Purchase,0.00,NaN,150000.0,Rural,Alborz

## Add Commodity Code Classification to Table

In [8]:
data_engine.add_classification(df, classification="ORIGINAL_1383", level=2, year=year)

,ID,Code,Provision_Method,Amount,Price,Expenditure,ORIGINAL_1383 - 2
0,10004004227,11112,Purchase,10.00,250000.0,2500000.0,cereals_and_cereal_products
1,10004004227,11142,Purchase,10.00,30000.0,300000.0,cereals_and_cereal_products
2,10004004227,11143,Purchase,10.00,30000.0,300000.0,cereals_and_cereal_products
3,10004004227,11174,Purchase,2.00,350000.0,700000.0,cereals_and_cereal_products
4,10004004227,11211,Purchase,2.00,1300000.0,2600000.0,meat
...,...,...,...,...,...,...,...
1127128,23003707026,11924,Non_Agricultural_Work,0.63,452380.0,285000.0,spices_culinary_and_other_food_products
1127129,23003707026,12112,Non_Agricultural_Work,0.50,2500000.0,1250000.0,tea_coffee_and_cocoa_drinks
1127130,23003707026,12212,Non_Agricultural_Work,0.00,NaN,200000.0,soft_drinks
1127131,23003707035,12211,Purchase,0.00,NaN,150000.0,soft_drinks
1127132,23003707035,12213,Purchase,0.00,NaN,150000.0,soft_drinks